### ISSUE TITLE
BUG: Private app access_token does not work

### ISSUE THREAD

**Issue by taylorsmithgg** [HubSpot/hubspot-api-python#129]
Using latest v6.0.0

Following instructions from: https://developers.hubspot.com/docs/api/private-apps#make-api-calls-with-your-app-s-access-token

```python
from hubspot import HubSpot

access_token = 'pat-rest-of-token'

api_client = HubSpot(access_token=access_token)
api_client.crm.imports.core_api.get_page()
```

Results in:
```
hubspot.crm.imports.exceptions.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 29 Sep 2022 21:06:39 GMT', 'Content-Type': 'application/json;charset=utf-8', 'Content-Length': '316', 'Connection': 'keep-alive', 'CF-Ray': '7527af13e9ed7db3-LAX', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'Vary': 'Accept-Encoding', 'CF-Cache-Status': 'DYNAMIC', 'Access-Control-Allow-Credentials': 'false', 'X-HubSpot-Auth-Failure': '401 Unauthorized', 'X-HubSpot-Correlation-Id': '6519ebb7-9fa1-41ad-a12a-228f806539cb', 'X-Trace': '2B317746049709A523DCDABB5C71F6719D878BDE70C111868E15F3192301', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=bdUBX%2Fk4mZI2nT22XevCtKBx142CmD8lm1IaJC3zSmk1umamXGQdpuqbi%2BJX7X%2F1e%2FWs66IzAvsviZwzGWHV7D%2FBUjNcZeVnMCAH%2F6NKURzX3XDcE03%2BrvTz4%2FUWnodM"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'})
HTTP response body: {"status":"error","message":"Authentication credentials not found. This API supports both API Key and OAuth 2.0 authentication and you can find more details at https://developers.hubspot.com/docs/methods/auth/oauth-overview","correlationId":"6519ebb7-9fa1-41ad-a12a-228f806539cb","category":"INVALID_AUTHENTICATION"}
```

**Comment by tylergibson** [comment]
+1 to this, encountering the same error.  The same call works through manual requests post.

This only seems to be affecting core_api - calls to basic_api work as expected.

**Comment by cdelacombaz** [comment]
This has been fixed on version 7.0.0

**Comment by adam-ag5** [comment]
@cdelacombaz I have updated to version 7.0.0, and I am still getting the same error when creating an import

```py
client.crm.imports.core_api.create(async_req=False, files=[csv_file], import_request=import_request)
```

response Headers:

```json
{
    "Date": "Mon, 28 Nov 2022 10:10:39 GMT",
    "Content-Type": "application/json;charset=utf-8",
    "Content-Length": "316",
    "Connection": "keep-alive",
    "CF-Ray": "7712509d3810920b-FRA",
    "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
    "Vary": "origin, Accept-Encoding",
    "CF-Cache-Status": "DYNAMIC",
    "Access-Control-Allow-Credentials": "false",
    "X-HubSpot-Auth-Failure": "401 Unauthorized",
    "X-HubSpot-Correlation-Id": "351870e8-7012-42e4-a402-089656a5f407",
    "X-Trace": "2B2DC262170D5BE540A5AB1BB3CBBC8BEC779695F5B0DF0B7FBCDC7E1601",
    "Report-To": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=%2BbZhm4%2FHKw0FlPGRdQQYcnwRIrYj6qe5WDTdpk1M1QrbmtUpZ8xmQWch%2BM41lVowWZEpY1ihGnuNSouMsnejf5hZTcCejt9eYljXTuFzrXgCFSgiYvnk891mpwLmA65t\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
    "NEL": "{\"success_fraction\":0.01,\"report_to\":\"cf-nel\",\"max_age\":604800}",
    "Server": "cloudflare",
    "alt-svc": "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400"
}
```

response Body:
```json
{
    "status": "error",
    "message": "Authentication credentials not found. This API supports both API Key and OAuth 2.0 authentication and you can find more details at https://developers.hubspot.com/docs/methods/auth/oauth-overview",
    "correlationId": "351870e8-7012-42e4-a402-089656a5f407",
    "category": "INVALID_AUTHENTICATION"
}
```

**Comment by cdelacombaz** [comment]
For me it works with a private app using this code:

```python
import hubspot
client = hubspot.Client.create(access_token=os.environ.get('SECRET_HUBSPOT_API_KEY'))
client.crm.deals.basic_api.get_by_id(id)
```

I am using v7.0.0.
My comment that it was fixed relates to following change 17 days ago, which made it to v7:
https://github.com/HubSpot/hubspot-api-python/commit/2e44d22754f1e852716a185000dd6333f23bce80#diff-2a54094430f5616945e5c513539d1b504cdeccc8718f918fad1eab6fa470107c
=> check out hubspot/crm/schemas/api/core_api.py where following code has been changed in multiple places:

```python
 auth_settings = ["hapikey"]  # noqa: E501
 auth_settings = ["hapikey", "oauth2"]  # noqa: E501
```

This is also the change that was done to fix the private app issue temporarly in the fork mentioned here: https://github.com/HubSpot/hubspot-api-python/issues/132

**Comment by adam-ag5** [comment]
> For me it works with a private app using this code:
> 
> ```python
> import hubspot
> client = hubspot.Client.create(access_token=os.environ.get('SECRET_HUBSPOT_API_KEY'))
> client.crm.deals.basic_api.get_by_id(id)
> ```
> 
> I am using v7.0.0. My comment that it was fixed relates to following change 17 days ago, which made it to v7: [2e44d22#diff-2a54094430f5616945e5c513539d1b504cdeccc8718f918fad1eab6fa470107c](https://github.com/HubSpot/hubspot-api-python/commit/2e44d22754f1e852716a185000dd6333f23bce80#diff-2a54094430f5616945e5c513539d1b504cdeccc8718f918fad1eab6fa470107c) => check out hubspot/crm/schemas/api/core_api.py where following code has been changed in multiple places:
> 
> ```python
>  auth_settings = ["hapikey"]  # noqa: E501
>  auth_settings = ["hapikey", "oauth2"]  # noqa: E501
> ```
> 
> This is also the change that was done to fix the private app issue temporarly in the fork mentioned here: #132

my bad, I did not include the creation of the client in my code snippet.
I am also using a private app which has the scope set to `crm.import` and am passing the `access_token` parameter.

```py
access_token = os.environ.get("HUBSPOT_ACCESS_TOKEN")
client = HubSpot(access_token=access_token)
```

But then when I call the endpoint I get the error in the [comment above](https://github.com/HubSpot/hubspot-api-python/issues/129#issuecomment-1328841100) I get the error.
