### ISSUE TITLE
OAuth initialization fails; "'Discovery' object has no attribute 'default_api'"

### ISSUE THREAD

**Issue by neeDig** [HubSpot/hubspot-api-python#93]
Hi folks, 
Just started using this library, but I cannot get set up, because there seems to be an issue with the code to create an OAuth access token. I just used the example code from the documentation (with valid credentials):
```
from hubspot import HubSpot
from hubspot.auth.oauth import ApiException

api_client = HubSpot()

try:
    tokens = api_client.auth.oauth.default_api.create_token(
        grant_type="authorization_code",
        redirect_uri='<redirect-uri>',
        client_id='<client_id>',
        client_secret='<client_secret>',
        code='code'
    )
except ApiException as e:
    print("Exception when calling create_token method: %s\n" % e)
```

However, this led to this error:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    tokens = api_client.auth.oauth.default_api.create_token(
AttributeError: 'Discovery' object has no attribute 'default_api'
```

Python version is 3.8, package version is 4.0.6.
Thanks!

**Comment by Disruption** [comment]
I'm having exactly the same issue. Surprised there is no response at all so far in 2 weeks. 
This code comes from the api docs itself and it doesn't run...

**Comment by Disruption** [comment]
@neeDig  browsing a bit, I saw that there is no "default_api" field on the oauth discovery anymore.

Try replacing "default_api" by "tokens_api" on this line:
`tokens = api_client.auth.oauth.default_api.create_token(`
so it becomes:
`tokens = api_client.auth.oauth.tokens_api.create_token(`

**Comment by plaurynovich-hubspot** [comment]
It should be fixed now. Thank you.

**Comment by Ghost93** [comment]
Hi, FYI, this is still happening in `hubspot-api-client==6.0.0`
